### PR TITLE
SynchrString Synchronization with Updates

### PR DESCRIPTION
**Pull request by ehcho0222**

### CODE REVIEW

**Comment by pmotschmann** [comment]
This needs to be squished into one commit

**Comment by ehcho0222** [comment]
How can I do it?

**Comment by justino** [comment]
You also seemed to have accidentally committed a change to the `.gitignore` file, might want to remove that

**Comment by Rodrigodd** [comment]
And you should delete all the lines marked with 'TRANS:' before making a pull request.
And if the translated strings files does not contain a key, the game will use the english string instead (this information probably needs to be added to the readme), so it is better not keep untranslated strings in the file.

**Pull request closed without merging**
