### PR TITLE
Add "Dread Not" feat

### PR DESCRIPTION
**Pull request by jacob-keller**
The achievement "Dreaded" is earned if you ascend without owning
a dreadnought. It's possible to earn this achievement if you've
constructed a dreadnought but it was destroyed in an assault. The
description of the achievement doesn't make this obvious.

Introduce a new feat, "Dread Not" which is earned only if you ascend
without building even a single Dreadnought. Update the description of
Dreaded to mention that you must ascend without owning any Dreadnoughts.

### CODE REVIEW

**Comment by jacob-keller** [comment]
@Beorseder  any particular reason for thumbs down? I guess the "Dread Not" feat isn't really necessary, but I do think the description for dreaded should be updated to be clear that it isn't strictly about building them (in light of how you can manage to build and destroy one dreadnought and still get it).

**Comment by Beorseder** [comment]
Yeah thumbs down was just for the feat. imo it's basically the same thing as the achievement. It's marginally more difficult to do it without building any than if you do build one and sack it, so much so that people probably would just not build one at all so they could get both the achievement and feat on the same run. Originally that's how the achievement was earned anyways. You weren't able to lose Dreadnoughts to Chthonian when it was first implemented, and so the achievement had to be done by not building any at all, which is why the achievement says that. Update the achievement description sure, or make the achievement match its description so that building any Dreadnoughts invalidates getting the achievement for that run, but don't see a reason to add a feat that's basically the same thing as an already existing achievement.

**Comment by pmotschmann** [comment]
This isn't worth a feat

**Comment by jacob-keller** [comment]
I opened a different PR to just fix the description :)

**Pull request closed without merging**
