### PR TITLE
Update es-ES

### PR DESCRIPTION
**Pull request by RanaPeluda**

### CODE REVIEW

**Comment by RanaPeluda** [comment]
After this update, the translation does not work, I have checked if I placed "." instead of "," but I don't see that fault, I don't know what I've broken.

**Comment by RanaPeluda** [comment]
Perhaps it is that on the last line before "}" does not lead ","?

**Comment by pmotschmann** [comment]
the last line can not have a comma, that makes the json invalid

**Comment by pmotschmann** [comment]
I fixed the issue

**Pull request merged**
