### PR TITLE
Token Expansion

### PR DESCRIPTION
**Pull request by Beorseder**
Added alphabetical tokens a-z to expand  the number of possible tokens in a string past 10.

### CODE REVIEW

**Comment by Rodrigodd** [comment]
hmm, I thought this code already worked for tokens larger than 10. But I have not tested.

**Comment by Beorseder** [comment]
You can notice that it won't work for tokens larger than 10, if you roll 6 geology traits. It doesn't work because when the code looks for any instances of %1 in the string to be replaced, it also replaces the %1 in front of %10, %11, %12, etc. So you'll get something like in the image below, where the second variable of Iron incorrectly replaces the %1 part of the 11th and 12th tokens.
Token Bug

**Comment by pmotschmann** [comment]
Nothing should need this many tokens, i'm going in a different direction.

**Comment by Rodrigodd** [comment]
The regex `%${i}(?!\d)` was supposed to match only if after the token there is not a number.
The javascript `new RegExp(`%${i}(?!\d)`, "g")` don't support lookaheads.
But the syntax `\%${i}(?!\d)\`  support it.

**Pull request closed without merging**
