### PR TITLE
update localization

### PR DESCRIPTION
**Pull request by Rodrigodd**
I think I ended the localization (maybe not).
I'm going to start doing the translation to pt-BR, and as I'll be looking at all the strings one by one, I'll also fix anything I find.

### CODE REVIEW

**Comment by pmotschmann** [comment]
This is causing a large number of breaking errors.

errors

**Comment by Rodrigodd** [comment]
I think I've fixed the problems, at least the ones I saw in the picture.
And I also made the loc function errors not break the whole game.

**Comment by pmotschmann** [comment]
I pulled this into the 0.4.21 branch, it will go out with the next update.

**Comment by pmotschmann** [comment]
On a side note.... there is actually a whole lot of stuff in actions.js that needs to be pulled out into the stings file under the tech section. I've been slowing working on the actions.js file but the bulk of the game is in there and it's taking a long time. The tech section is the only part left, everything upto currency is done at this time. If you want to focus on the existing translations you can backfilll this section later as I get them refactored out.

**Comment by Rodrigodd** [comment]
No, I can do the refactor of this part too.

**Comment by Rodrigodd** [comment]
I finished the tech localization.
Try test it in a save with all the research completes, if you have one, to see if exist errors there.

**Comment by pmotschmann** [comment]
Looks pretty good overall, There were a a few minor problems I spotted but I fixed them.

**Pull request merged**
